import { StitchScreen, ScreenCategory } from '../types/download';

export const STITCH_SCREENS: StitchScreen[] = [
  // Batch 1 - Customer Screens (10 screens)
  {
    id: '01-Staff-Login-Desktop',
    name: 'Staff Login',
    title: 'Staff Login Screen',
    description: 'Desktop login page for kitchen and waiter staff',
    category: 'shared',
    roles: [2, 3, 4], // Admin, Kitchen, Waiter
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/01-Staff-Login-Desktop/screenshot.png',
    htmlUrl: '/stitch-screens/01-Staff-Login-Desktop/code.html',
    order: 1,
    tags: ['auth', 'desktop', 'login'],
    estimatedFileSize: { html: 7.01, screenshot: 84.04 },
  },
  {
    id: '02-Waiter-Floor-Plan',
    name: 'Waiter: Floor Plan',
    title: 'Floor Plan & Table Management',
    description: 'Desktop view of restaurant floor with table status',
    category: 'waiter',
    roles: [2, 4], // Admin, Waiter
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/02-Waiter-Floor-Plan/screenshot.png',
    htmlUrl: '/stitch-screens/02-Waiter-Floor-Plan/code.html',
    order: 2,
    tags: ['tables', 'desktop', 'waiter'],
    estimatedFileSize: { html: 20.76, screenshot: 66.95 },
  },
  {
    id: '03-Kitchen-Order-Detail',
    name: 'Kitchen: Order Detail',
    title: 'Kitchen Order Details View',
    description: 'Desktop view showing detailed order information',
    category: 'kitchen',
    roles: [2, 3], // Admin, Kitchen
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2064,
    screenshotUrl: '/stitch-screens/03-Kitchen-Order-Detail/screenshot.png',
    htmlUrl: '/stitch-screens/03-Kitchen-Order-Detail/code.html',
    order: 3,
    tags: ['orders', 'desktop', 'kitchen'],
    estimatedFileSize: { html: 14.08, screenshot: 52.42 },
  },
  {
    id: '04-Customer-Login',
    name: 'Customer Login',
    title: 'Customer Login Screen',
    description: 'Mobile login page for customers',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 1768,
    screenshotUrl: '/stitch-screens/04-Customer-Login/screenshot.png',
    htmlUrl: '/stitch-screens/04-Customer-Login/code.html',
    order: 4,
    tags: ['auth', 'mobile', 'login'],
    estimatedFileSize: { html: 6.92, screenshot: 57.12 },
  },
  {
    id: '05-Customer-Live-Status',
    name: 'Customer: Live Status',
    title: 'Order Live Status Tracking',
    description: 'Mobile view of real-time order status updates',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 2032,
    screenshotUrl: '/stitch-screens/05-Customer-Live-Status/screenshot.png',
    htmlUrl: '/stitch-screens/05-Customer-Live-Status/code.html',
    order: 5,
    tags: ['orders', 'mobile', 'tracking'],
    estimatedFileSize: { html: 7.69, screenshot: 38.14 },
  },
  {
    id: '06-Kitchen-KDS-Dashboard',
    name: 'Kitchen: KDS Dashboard',
    title: 'Kitchen Display System',
    description: 'Desktop KDS showing active orders queue',
    category: 'kitchen',
    roles: [2, 3], // Admin, Kitchen
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/06-Kitchen-KDS-Dashboard/screenshot.png',
    htmlUrl: '/stitch-screens/06-Kitchen-KDS-Dashboard/code.html',
    order: 6,
    tags: ['orders', 'desktop', 'kds'],
    estimatedFileSize: { html: 19.53, screenshot: 82.81 },
  },
  {
    id: '07-Admin-Dashboard',
    name: 'Admin: Dashboard',
    title: 'Admin Control Dashboard',
    description: 'Main admin dashboard with system overview',
    category: 'admin',
    roles: [2], // Admin only
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/07-Admin-Dashboard/screenshot.png',
    htmlUrl: '/stitch-screens/07-Admin-Dashboard/code.html',
    order: 7,
    tags: ['admin', 'desktop', 'dashboard'],
    estimatedFileSize: { html: 20.82, screenshot: 69.77 },
  },
  {
    id: '08-Waiter-Order-Entry',
    name: 'Waiter: Order Entry',
    title: 'Order Entry for Proxy Orders',
    description: 'Desktop interface for waiters to enter customer orders',
    category: 'waiter',
    roles: [2, 4], // Admin, Waiter
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/08-Waiter-Order-Entry/screenshot.png',
    htmlUrl: '/stitch-screens/08-Waiter-Order-Entry/code.html',
    order: 8,
    tags: ['orders', 'desktop', 'waiter'],
    estimatedFileSize: { html: 18.86, screenshot: 131.94 },
  },
  {
    id: '09-QR-Scan-Required-Popup',
    name: 'QR Scan Required Popup',
    title: 'QR Code Scanner Prompt',
    description: 'Mobile popup prompting customer to scan QR code',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 1768,
    screenshotUrl: '/stitch-screens/09-QR-Scan-Popup/screenshot.png',
    htmlUrl: '/stitch-screens/09-QR-Scan-Popup/code.html',
    order: 9,
    tags: ['qr', 'mobile', 'auth'],
    estimatedFileSize: { html: 8.32, screenshot: 29.92 },
  },
  {
    id: '10-Customer-Menu',
    name: 'Customer: Menu',
    title: 'Menu Browse Screen',
    description: 'Mobile menu browsing with search & filter',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 3922,
    screenshotUrl: '/stitch-screens/10-Customer-Menu/screenshot.png',
    htmlUrl: '/stitch-screens/10-Customer-Menu/code.html',
    order: 10,
    tags: ['menu', 'mobile', 'browse'],
    estimatedFileSize: { html: 11.45, screenshot: 61.96 },
  },
  {
    id: '11-Admin-Menu-Management',
    name: 'Admin: Menu Management',
    title: 'Menu Items Management',
    description: 'Admin interface to manage menu items and categories',
    category: 'admin',
    roles: [2], // Admin only
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/11-Admin-Menu-Management/screenshot.png',
    htmlUrl: '/stitch-screens/11-Admin-Menu-Management/code.html',
    order: 11,
    tags: ['admin', 'desktop', 'menu'],
    estimatedFileSize: { html: 15.71, screenshot: 48 },
  },
  {
    id: '12-Customer-Checkout',
    name: 'Customer: Checkout',
    title: 'Checkout Page',
    description: 'Mobile checkout and payment confirmation',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 1912,
    screenshotUrl: '/stitch-screens/12-Customer-Checkout/screenshot.png',
    htmlUrl: '/stitch-screens/12-Customer-Checkout/code.html',
    order: 12,
    tags: ['checkout', 'mobile', 'payment'],
    estimatedFileSize: { html: 9.27, screenshot: 36.82 },
  },
  {
    id: '13-Customer-Register',
    name: 'Customer Register',
    title: 'Customer Registration Screen',
    description: 'Mobile registration page for new customers',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 1950,
    screenshotUrl: '/stitch-screens/13-Customer-Register/screenshot.png',
    htmlUrl: '/stitch-screens/13-Customer-Register/code.html',
    order: 13,
    tags: ['auth', 'mobile', 'register'],
    estimatedFileSize: { html: 6.82, screenshot: 41.15 },
  },
  {
    id: '14-Kitchen-Inventory-Management',
    name: 'Kitchen: Inventory Management',
    title: 'Inventory Management System',
    description: 'Desktop inventory tracking and management',
    category: 'kitchen',
    roles: [2, 3], // Admin, Kitchen
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2218,
    screenshotUrl: '/stitch-screens/14-Kitchen-Inventory/screenshot.png',
    htmlUrl: '/stitch-screens/14-Kitchen-Inventory/code.html',
    order: 14,
    tags: ['inventory', 'desktop', 'management'],
    estimatedFileSize: { html: 20.96, screenshot: 63.37 },
  },
  {
    id: '15-Customer-Profile-Settings',
    name: 'Customer Profile & Settings',
    title: 'Customer Profile Management',
    description: 'Mobile profile and settings page for customers',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 2650,
    screenshotUrl: '/stitch-screens/15-Customer-Profile/screenshot.png',
    htmlUrl: '/stitch-screens/15-Customer-Profile/code.html',
    order: 15,
    tags: ['profile', 'mobile', 'settings'],
    estimatedFileSize: { html: 10.53, screenshot: 31.08 },
  },
  {
    id: '16-Customer-Cart-Overlay',
    name: 'Customer Cart Overlay',
    title: 'Shopping Cart Overlay',
    description: 'Mobile shopping cart overlay interface',
    category: 'customer',
    roles: [1, 2], // Customer, Admin
    deviceType: 'MOBILE',
    width: 780,
    height: 1768,
    screenshotUrl: '/stitch-screens/16-Customer-Cart-Overlay/screenshot.png',
    htmlUrl: '/stitch-screens/16-Customer-Cart-Overlay/code.html',
    order: 16,
    tags: ['cart', 'mobile', 'overlay'],
    estimatedFileSize: { html: 10.13, screenshot: 45.01 },
  },
  // Batch 2 - Additional 7 screens
  {
    id: '17-Admin-Staff-Management',
    name: 'Admin: Staff Management',
    title: 'Staff Member Management',
    description: 'Desktop interface for managing kitchen and waiter staff',
    category: 'admin',
    roles: [2], // Admin only
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/17-Admin-Staff-Management/screenshot.png',
    htmlUrl: '/stitch-screens/17-Admin-Staff-Management/code.html',
    order: 17,
    tags: ['admin', 'desktop', 'staff'],
    estimatedFileSize: { html: 19.41, screenshot: 95.23 },
  },
  {
    id: '18-Waiter-Profile-Stats',
    name: 'Waiter Profile & Stats',
    title: 'Waiter Performance Dashboard',
    description: 'Desktop view of waiter profile and shift statistics',
    category: 'waiter',
    roles: [2, 4], // Admin, Waiter
    deviceType: 'DESKTOP',
    width: 2560,
    height: 3066,
    screenshotUrl: '/stitch-screens/18-Waiter-Profile-Stats/screenshot.png',
    htmlUrl: '/stitch-screens/18-Waiter-Profile-Stats/code.html',
    order: 18,
    tags: ['stats', 'desktop', 'waiter'],
    estimatedFileSize: { html: 23.08, screenshot: 78.45 },
  },
  {
    id: '19-Inventory-Alerts-Reorder',
    name: 'Inventory Alerts & Reorder',
    title: 'Inventory Alerts System',
    description: 'Desktop view for inventory alerts and reorder management',
    category: 'admin',
    roles: [2], // Admin only
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/19-Inventory-Alerts-Reorder/screenshot.png',
    htmlUrl: '/stitch-screens/19-Inventory-Alerts-Reorder/code.html',
    order: 19,
    tags: ['inventory', 'desktop', 'alerts'],
    estimatedFileSize: { html: 15.12, screenshot: 72.31 },
  },
  {
    id: '20-Waiter-History-Shift-Summary',
    name: 'Waiter: History & Shift Summary',
    title: 'Waiter Shift History',
    description: 'Desktop shift history and performance summary',
    category: 'waiter',
    roles: [2, 4], // Admin, Waiter
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2292,
    screenshotUrl: '/stitch-screens/20-Waiter-History-Shift-Summary/screenshot.png',
    htmlUrl: '/stitch-screens/20-Waiter-History-Shift-Summary/code.html',
    order: 20,
    tags: ['history', 'desktop', 'waiter'],
    estimatedFileSize: { html: 18.67, screenshot: 81.92 },
  },
  {
    id: '21-Admin-Reports-Analytics',
    name: 'Admin: Reports & Analytics',
    title: 'Analytics & Reporting Dashboard',
    description: 'Desktop analytics and business intelligence dashboard',
    category: 'admin',
    roles: [2], // Admin only
    deviceType: 'DESKTOP',
    width: 2560,
    height: 3408,
    screenshotUrl: '/stitch-screens/21-Admin-Reports-Analytics/screenshot.png',
    htmlUrl: '/stitch-screens/21-Admin-Reports-Analytics/code.html',
    order: 21,
    tags: ['analytics', 'desktop', 'reports'],
    estimatedFileSize: { html: 24.53, screenshot: 104.67 },
  },
  {
    id: '22-Kitchen-Order-History',
    name: 'Kitchen: Order History',
    title: 'Order History & Archive',
    description: 'Desktop view of kitchen order history',
    category: 'kitchen',
    roles: [2, 3], // Admin, Kitchen
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/22-Kitchen-Order-History/screenshot.png',
    htmlUrl: '/stitch-screens/22-Kitchen-Order-History/code.html',
    order: 22,
    tags: ['orders', 'desktop', 'history'],
    estimatedFileSize: { html: 16.89, screenshot: 88.14 },
  },
  {
    id: '23-Staff-Admin-Account-Settings',
    name: 'Staff & Admin Account Settings',
    title: 'Account Settings & Preferences',
    description: 'Desktop settings page for staff and admin accounts',
    category: 'admin',
    roles: [2, 3, 4], // Admin, Kitchen, Waiter
    deviceType: 'DESKTOP',
    width: 2560,
    height: 2048,
    screenshotUrl: '/stitch-screens/23-Staff-Admin-Account-Settings/screenshot.png',
    htmlUrl: '/stitch-screens/23-Staff-Admin-Account-Settings/code.html',
    order: 23,
    tags: ['settings', 'desktop', 'account'],
    estimatedFileSize: { html: 17.42, screenshot: 92.58 },
  },
];

export const SCREEN_CATEGORIES: ScreenCategory[] = [
  {
    id: 'customer',
    name: 'Customer Screens',
    path: '/downloads/customer',
    description: 'Mobile-first customer-facing UI screens',
    screenCount: 9,
    icon: '👥',
  },
  {
    id: 'admin',
    name: 'Admin Screens',
    path: '/downloads/admin',
    description: 'Administrative dashboards & management tools',
    screenCount: 7,
    icon: '⚙️',
  },
  {
    id: 'kitchen',
    name: 'Kitchen Screens',
    path: '/downloads/kitchen',
    description: 'Kitchen display systems & order management',
    screenCount: 4,
    icon: '👨‍🍳',
  },
  {
    id: 'waiter',
    name: 'Waiter Screens',
    path: '/downloads/waiter',
    description: 'Waiter service & order management screens',
    screenCount: 3,
    icon: '🧑‍💼',
  },
];

export const DOWNLOAD_BASE_PATH = '/stitch-screens';
